### ISSUE TITLE
QM Bug 002 - Used Potions Not Destroyed (Major)

### ISSUE THREAD

**Issue by VarSnow** [GobblersInc/Turbulent-Tinctures#97]
https://github.com/user-attachments/assets/92fac5c1-a824-465a-88e3-f6082996823c

Steps to reproduce:
Unknown at this time. 
May be caused by collision with meshes.

**Comment by VarSnow** [comment]
Similar to "Infinite potions" bug.

**Comment by VarSnow** [comment]
Other similar issue: https://github.com/GobblersInc/Turbulent-Tinctures/issues/95

**Comment by matthew-c-lee** [comment]
fixed
